### ISSUE TITLE
I do not love Elana

### ISSUE THREAD

**Issue by renaissancedog** [reagan-schedule/reagan-schedule.github.io#2]
I do not, in fact, love Elana

**Comment by elmcitydavid** [comment]
Please provide steps to reproduce the issue

**Comment by renaissancedog** [comment]
The issue is in the commit history.

**Comment by elmcitydavid** [comment]
Fixed

**Comment by renaissancedog** [comment]
that's better

**Comment by elmcitydavid** [comment]
Why did you edit it?
Was your original comment something along the lines of 'William loves Elana?'
